---

- name: Gather user fact
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "user"
  when:
    - ansible_user is undefined

- name: Ensure base directory for health checks exists
  become: true
  ansible.builtin.file:
    path: /var/lib/openstack/healthchecks
    state: directory
    setype: container_file_t
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: '0755'

- name: Deploy ovn_metadata_agent health check script
  become: true
  ansible.builtin.copy:
    src: healthchecks/ovn_metadata_agent/
    dest: /var/lib/openstack/healthchecks/ovn_metadata_agent
    setype: container_file_t
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: '0700'
